# Statitistical Learning Lab

## Data Types, Arrays and Basics

In [1]:
print('fit a model with', 11, 'variables')

fit a model with 11 variables


In [7]:
# list concatenation
x = [1, "yeah baby", 3]
y = [4, 5, True]

x + y 

[1, 'yeah baby', 3, 4, 5, True]

## Tuples


In [30]:
my_tuple = (3, 4, 5)
my_tuple[0] 

3

In [32]:
# tuples are immutable
my_tuple[0] = 2

TypeError: 'tuple' object does not support item assignment

## Numpy

In [10]:
import numpy as np

In [12]:
# adding arrays
x = np.array([1, 2, 3])
y = np.array([5, 7, 9])

In [14]:
z = x + y
z

array([ 6,  9, 12])

### Array Attributes

In [16]:
# number of dimension
x.ndim

1

In [17]:
# data type
x.dtype

dtype('int64')

In [18]:
# array shape
x.shape

(3,)

### Methods

In [19]:
# array sum
z.sum()

27

In [20]:
# array mean
z.mean()

9.0

array([ 6,  9, 12])

In [28]:
# array reshape
w = np.array([1, 2, 3, 4, 5, 6])
print('start w:\n', w)
w_reshaped = w.reshape((2, 3)) # accepts a tuple of two numerical values in the format (rows, columns)
print('end w:\n', w_reshaped)
w_reshaped.shape

start w:
 [1 2 3 4 5 6]
end w:
 [[1 2 3]
 [4 5 6]]


(2, 3)

In [29]:
print('pre-modification w:\n', w)
print('pre-modification w_reshaped:\n', w_reshaped)
w_reshaped[1, 1] = 7 # changed the second element in second array to  7 from 5
print('post-modification w:\n', w)
print('post-modification w_reshaped:\n', w_reshaped)
# changes reflect in both 'w' array and 'w_reshaped' matrix because both reference the same space in memory

pre-modification w:
 [1 2 3 4 5 6]
pre-modification w_reshaped:
 [[1 2 3]
 [4 5 6]]
post-modification w:
 [1 2 3 4 7 6]
post-modification w_reshaped:
 [[1 2 3]
 [4 7 6]]


In [37]:
w_transpose = w_reshaped.T
print('original reshape:\n', w_reshaped)
print('original shape:', w_reshaped.shape)
print('transposed matrix:\n', w_transpose)
print('transpose shape:', w_transpose.shape)

original reshape:
 [[1 2 3]
 [4 7 6]]
original shape: (2, 3)
transposed matrix:
 [[1 4]
 [2 7]
 [3 6]]
transpose shape: (3, 2)


In [39]:
w_squared = w ** 2 # squaring all numbers in a matrix
w_squared

array([ 1,  4,  9, 16, 49, 36])

In [41]:
w_root  = np.sqrt(w) # square root of all numbers
print('w_root dtype:', w_root.dtype)
w_root


w_root dtype: float64


array([1.        , 1.41421356, 1.73205081, 2.        , 2.64575131,
       2.44948974])

## Random Numbers

In [43]:
x = np.random.normal(size=50) # vector of 50 random numbers 
x

array([-0.46554318, -0.79673534,  0.99908655, -0.76129324, -1.69023404,
        0.54340275, -1.03618135, -0.35555361, -0.83460833,  0.4963494 ,
        0.6840348 , -0.27964507, -0.78258765, -0.22800486, -0.24688422,
       -0.59361446,  0.82396778, -2.95824742,  0.03776546,  1.13266011,
        1.29106038,  1.26402032, -1.28787238,  0.89861714,  0.02353533,
       -0.1753472 ,  1.82177487, -0.23833831,  0.62518813,  1.22517299,
        0.87512254,  0.00384089,  1.85797236,  0.96956394,  0.1725828 ,
       -0.42269805, -0.76621833, -0.22413444, -1.20205979, -0.14142435,
        0.07608631,  0.28886741,  2.13876376,  1.35278524, -0.88350298,
        0.06894849,  0.83415443, -1.24386257, -1.23989251, -0.07079066])

In [45]:
y = x + np.random.normal(loc=50, scale=1, size=50) # addind an independant random variable to each element of X
y

array([48.72799222, 49.39925303, 50.66971418, 49.09161205, 49.23647331,
       51.22113854, 47.39262869, 49.84681006, 48.46974946, 49.66145544,
       50.67738222, 49.90895495, 48.80204447, 50.85039672, 50.77894356,
       49.7427931 , 52.06553522, 46.73578849, 48.16559133, 51.18294286,
       51.71399711, 50.21059051, 47.86934394, 49.82924375, 49.97113598,
       48.7152793 , 51.41112754, 49.4709292 , 51.54605799, 51.15606213,
       51.33531992, 50.52420089, 52.48647627, 51.44435174, 51.52865763,
       50.87102628, 48.43806456, 50.53152842, 48.89579462, 50.01859827,
       49.87532694, 50.54249457, 52.77397385, 50.32532341, 48.56135399,
       51.03604064, 50.68154983, 48.94504598, 49.29764011, 51.55510261])

In [46]:
np.corrcoef(x, y) # correlation coefficient between x and y

array([[1.        , 0.80321174],
       [0.80321174, 1.        ]])

In [49]:
print(np.random.normal(scale=5, size=2))
print(np.random.normal(scale=5, size=2))
# each an np.random function is run a different result is produced

[-13.06137217  -9.50567146]
[ 6.97435374 -0.85826475]


In [52]:
np.random.default_rng?

Docstring:
default_rng(seed=None)
Construct a new Generator with the default BitGenerator (PCG64).

    Parameters
    ----------
    seed : {None, int, array_like[ints], SeedSequence, BitGenerator, Generator}, optional
        A seed to initialize the `BitGenerator`. If None, then fresh,
        unpredictable entropy will be pulled from the OS. If an ``int`` or
        ``array_like[ints]`` is passed, then it will be passed to
        `SeedSequence` to derive the initial `BitGenerator` state. One may also
        pass in a `SeedSequence` instance.
        Additionally, when passed a `BitGenerator`, it will be wrapped by
        `Generator`. If passed a `Generator`, it will be returned unaltered.

    Returns
    -------
    Generator
        The initialized generator object.

    Notes
    -----
    If ``seed`` is not a `BitGenerator` or a `Generator`, a new `BitGenerator`
    is instantiated. This function does not manage a default global instance.

    See :ref:`seeding_and_entropy` 

In [54]:
rng = np.random.default_rng(1303) # setting the seed for np.random to make generator results reproducible 
print(rng.normal(scale=5, size=2)) 
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale=5, size=2))

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]
